{% set name = "country_converter" %}
{% set version = "1.2" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/country_converter-{{ version }}.tar.gz
  sha256: 74e87db54b91eda56c5eecc9e36e1b5ca79ca2bca58012ecc4f55ef8a13a6631

build:
  number: 0
  noarch: python
  entry_points:
    - coco = country_converter.country_converter:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - pandas >=1.0.0
    - python >={{ python_min }}

test:
  imports:
    - country_converter
  commands:
    - pip check
    - coco --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/IndEcol/country_converter
  summary: The country converter (coco) - a Python package for converting country names between different classifications schemes.
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: |
    The country converter (coco) is a Python package to convert and match 
    country names between different classifications and between different 
    naming versions. Internally it uses regular expressions to match country 
    names. Coco can also be used to build aggregation concordance matrices 
    between different classification schemes.
  doc_url: https://github.com/IndEcol/country_converter
  dev_url: https://github.com/IndEcol/country_converter/blob/master/CONTRIBUTING.md


extra:
  recipe-maintainers:
    - konstantinstadler
