{% set name = "country_converter" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/country_converter-{{ version }}.tar.gz
  sha256: 5a75dab296d79bf59b3ea836b0637b746821e5ad8444be465cda2472f2a17edb

build:
  number: 0
  noarch: python
  entry_points:
    - coco = country_converter.country_converter:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pandas >=0.17.0
    - python >=3.6

test:
  imports:
    - country_converter
  commands:
    - pip check
    - coco --help
  requires:
    - pip

about:
  home: https://github.com/konstantinstadler/country_converter
  summary: The country converter (coco) - a Python package for converting country names between different classifications schemes.
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: |
    The country converter (coco) is a Python package to convert and match 
    country names between different classifications and between different 
    naming versions. Internally it uses regular expressions to match country 
    names. Coco can also be used to build aggregation concordance matrices 
    between different classification schemes.
  doc_url: https://github.com/konstantinstadler/country_converter
  dev_url: https://github.com/konstantinstadler/country_converter/blob/master/CONTRIBUTING.rst


extra:
  recipe-maintainers:
    - konstantinstadler
